language: bash
script:
- cat sample_travis_output.txt
after_success:
# get lucee version string
- "sleep 10s && curl -s \"https://api.travis-ci.org/v3/job/${TRAVIS_JOB_ID}/log.txt?deansi=true\" > travis_output.log"
- "export LUCEE_VERSION=$(grep -oP \"(?<=\\[INFO\\] Building Lucee Loader Build )(\\d+\\.\\d+\\.\\d+\\.\\d+(.*)?)\" travis_output.log)"
- echo "LUCEE_VERSION = $LUCEE_VERSION"
# trigger docker image build for this lucee version
- "export REQUEST_BODY=\"{\\\"request\\\": { \\\"message\\\": \\\"Testing automated build for version $LUCEE_VERSION\\\", \\\"branch\\\":\\\"travis-build-matrix\\\", \\\"config\\\": { \\\"merge_mode\\\": \\\"deep_merge\\\", \\\"env\\\": { \\\"global\\\": { \\\"LUCEE_VERSION\\\": \\\"$LUCEE_VERSION\\\" }}}}}\"\n"
- "curl -s -X POST -H \"Content-Type: application/json\" -H \"Accept: application/json\" -H \"Travis-API-Version: 3\" -H \"Authorization: token $TRAVIS_TOKEN\" -d \"$REQUEST_BODY\" https://api.travis-ci.org/repo/lucee%2Flucee-dockerfiles/requests\n"
